// Builds src/food/ifct.ts from the Indian Food Composition Tables 2017 (National Institute
// of Nutrition), as packaged in @ifct2017/compositions.
//   npm --workspace @rei/shared run build:ifct
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const csvPath = join(dirname(require.resolve('@ifct2017/compositions/package.json')), 'index.csv');
const out = join(dirname(fileURLToPath(import.meta.url)), '../src/food/ifct.ts');

/** Minimal RFC 4180 parser: quoted fields may hold commas and newlines. */
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') (field += '"'), i++;
      else if (ch === '"') quoted = false;
      else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') row.push(field), (field = '');
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(field), rows.push(row), (row = []), (field = '');
    } else field += ch;
  }
  if (field || row.length) row.push(field), rows.push(row);
  return rows.filter(r => r.length > 1);
}

const [head, ...body] = parseCsv(readFileSync(csvPath, 'utf8'));
const col = Object.fromEntries(head.map((h, i) => [h.split('; ').pop(), i]));

// Local names worth searching by: English, Hindi and the larger regional languages.
const LANGS = ['E', 'H', 'Mar', 'Tam', 'Tel', 'Kan', 'Mal', 'B', 'G', 'P'];

function localNames(lang) {
  const names = new Set();
  for (const part of lang.split(';')) {
    const m = /^\s*([A-Za-z., ]+?)\.\s+(.+?)\.?\s*$/.exec(part);
    if (!m) continue;
    const codes = m[1].split(',').map(s => s.trim().replace(/\.$/, ''));
    if (!codes.some(c => LANGS.includes(c))) continue;
    for (const n of m[2].replace(/\([^)]*\)/g, '').split(/[,/]/)) {
      const t = n.trim().toLowerCase();
      if (t.length > 1) names.add(t);
    }
  }
  return [...names].join(', ').slice(0, 140);
}

const r1 = v => Math.round((parseFloat(v) || 0) * 10) / 10;
const rows = body.map(r => {
  const code = r[col.code], name = r[col.name].trim();
  return [code, name, localNames(r[col.lang] ?? ''), r1(r[col.protcnt]), r1(r[col.choavldf]), r1(r[col.fatce]), r1(r[col.fibtg])];
});

writeFileSync(
  out,
  `// Generated by scripts/build-ifct.mjs from the Indian Food Composition Tables 2017
// (T. Longvah et al., National Institute of Nutrition, Hyderabad). Do not edit.
// Per 100 g edible portion, mostly raw: [code, name, local names, protein, carbs, fat, fibre].
export const IFCT: [string, string, string, number, number, number, number][] = ${JSON.stringify(rows).replace(/\],\[/g, '],\n  [').replace(/^\[\[/, '[\n  [').replace(/\]\]$/, '],\n]')};
`,
);
console.log(`Wrote ${rows.length} foods to ${out}`);
