// Builds src/food/usda.ts from the USDA SR Legacy rows of tempo-food-db (TempoLife,
// CC-BY-4.0; the USDA data itself is public domain).
//   npm --workspace @rei/shared run build:usda
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const src = join(dirname(require.resolve('tempo-food-db/package.json')), 'data/tempolife-foods.json');
const out = join(dirname(fileURLToPath(import.meta.url)), '../src/food/usda.ts');

const rows = JSON.parse(readFileSync(src, 'utf8')).filter(x => x.source === 'usda_sr_legacy' && x.kcal_per_100g != null);

// Several cuts share one name in this dataset; keep the median-calorie one per name.
const byName = new Map();
for (const x of rows) {
  const name = x.name.trim();
  if (!byName.has(name)) byName.set(name, []);
  byName.get(name).push(x);
}

/** FNV-1a, base 36: a stable id from the name, so favourites survive rebuilds. */
function hash(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 0x01000193) >>> 0;
  return h.toString(36);
}

const r1 = v => Math.round((v ?? 0) * 10) / 10;
const seen = new Set();
const foods = [...byName.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, xs]) => {
    const x = xs.sort((a, b) => a.kcal_per_100g - b.kcal_per_100g)[Math.floor(xs.length / 2)];
    let id = hash(name);
    while (seen.has(id)) id = hash(id + name);
    seen.add(id);
    // Names are capped at 80 characters (what your own foods allow), cut at a comma or space.
    const short = name.length <= 80 ? name : name.slice(0, 80).replace(/[,\s][^,\s]*$/, '').replace(/[,\s]+$/, '');
    return [id, short, Math.round(x.kcal_per_100g), r1(x.protein_g), r1(x.carbs_g), r1(x.fat_g)];
  });

writeFileSync(
  out,
  `// Generated by scripts/build-usda.mjs from tempo-food-db (USDA FoodData Central SR Legacy,
// public domain; packaged by TempoLife, tempolife.app, CC-BY-4.0). Do not edit.
// Per 100 g: [id, name, kcal, protein, carbs, fat].
export const USDA: [string, string, number, number, number, number][] = ${JSON.stringify(foods).replace(/\],\[/g, '],\n  [').replace(/^\[\[/, '[\n  [').replace(/\]\]$/, '],\n]')};
`,
);
console.log(`Wrote ${foods.length} foods to ${out}`);
